I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 154, in script
    Rau  "É o seu TCC?"
Exception: Sayer 'Rau' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 154, in script
    Rau  "É o seu TCC?"
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Rau' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Heart Beat 1.0
Wed Nov 16 09:03:17 2022
